# Generated by Django 4.2.5 on 2023-10-25 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('dni', models.IntegerField(unique=True, verbose_name='Dni')),
                ('matricula', models.CharField(primary_key=True, serialize=False, verbose_name='Matrícula')),
                ('especialidad', models.ManyToManyField(to='mediturnosApp.especialidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=30, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=150, verbose_name='Email')),
                ('dni', models.IntegerField(unique=True, verbose_name='Dni')),
                ('historia_clinica', models.CharField(primary_key=True, serialize=False, verbose_name='Historia Clínica')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cancelado', models.BooleanField()),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediturnosApp.paciente')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediturnosApp.medico')),
            ],
        ),
    ]
