# Generated by Django 4.2.5 on 2023-11-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediturnosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='especialidad',
            options={'verbose_name_plural': 'Especialidades'},
        ),
        migrations.AlterModelOptions(
            name='medicoespecialidad',
            options={'verbose_name_plural': 'Medico especialidades'},
        ),
        migrations.AlterModelOptions(
            name='turnos',
            options={'verbose_name': 'Turno', 'verbose_name_plural': 'Turnos'},
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='descripcion',
            field=models.TextField(default='', max_length=250, verbose_name='Descripción de la especialidad'),
        ),
    ]
