# Generated by Django 4.2.5 on 2023-11-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediturnosApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='imagen',
            field=models.ImageField(default='', upload_to='mediturnosApp/img'),
        ),
    ]
